"""Block a commit when staged content prose has not been through ``prose-critic``.

CLAUDE.md requires the ``prose-critic`` subagent on every new or edited content
file. That requirement used to be carried by a pre-commit *reminder*, which is
worth exactly as much as the attention of whoever is committing — an agent that
has decided (or been told by its session prompt) not to spawn subagents reads
the reminder, commits anyway, and the writing gate is gone. This turns the
reminder into a check.

**How it verifies.** Claude Code appends every session to a JSONL transcript
under ``~/.claude/projects/<slugged-repo-path>/``. Each assistant tool call is a
record with a ``timestamp`` and a ``message.content[]`` block of
``{"type": "tool_use", "name": "Agent", "input": {"subagent_type": ...}}``. So a
``prose-critic`` run is a fact on disk: find the Agent calls whose
``subagent_type`` is ``prose-critic``, keep the ones newer than the current HEAD
commit, and read the file paths out of their prompts.

**It fails closed, but only where it can see.** No transcript directory, or no
transcript touched since HEAD, means this is a hand commit, a container clone,
or another tool — nothing to check against, so the commit passes. A transcript
that exists and shows no critic run for a staged file blocks the commit.

**What it does not check.** Coverage is "a critic ran against this path since
the last commit," not "the critic saw these exact bytes." A file edited after
its critique still counts — which it must, since the edits that answer the
critic's flags necessarily come after it.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from collections.abc import Iterable, Iterator
from datetime import UTC, datetime
from pathlib import Path

CONTENT_DIRS = ("world", "characters", "sessions", "handouts", "references", "docs")

# Generated by build-index, not written by hand: requiring a style critique of a
# regenerated index table would fail commits that contain no prose at all.
GENERATED_NAMES = frozenset({"INDEX.md", "README.md"})

BYPASS_ENV = "PROSE_CRITIC_BYPASS"

AGENT_TOOL_NAMES = frozenset({"Agent", "Task"})
CRITIC_AGENT = "prose-critic"


def _git(repo_root: Path, *args: str) -> str:
    """Run git in ``repo_root`` and return stdout, or "" if the command fails."""
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_root), *args],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return ""
    return result.stdout if result.returncode == 0 else ""


def staged_content_files(repo_root: Path) -> list[str]:
    """Repo-relative paths of staged content markdown, minus generated files."""
    out = _git(
        repo_root,
        "diff",
        "--cached",
        "--name-only",
        "--diff-filter=ACM",
        "--",
        *CONTENT_DIRS,
    )
    files = []
    for line in out.splitlines():
        path = line.strip()
        if not path.endswith(".md"):
            continue
        if Path(path).name in GENERATED_NAMES:
            continue
        files.append(path)
    return sorted(files)


def head_commit_time(repo_root: Path) -> datetime:
    """Commit time of HEAD, or the epoch when there is no HEAD yet."""
    out = _git(repo_root, "log", "-1", "--format=%cI").strip()
    if not out:
        return datetime.fromtimestamp(0, tz=UTC)
    try:
        return datetime.fromisoformat(out)
    except ValueError:
        return datetime.fromtimestamp(0, tz=UTC)


def transcript_dir(repo_root: Path, home: Path | None = None) -> Path:
    """The ~/.claude/projects directory Claude Code writes this repo's sessions to."""
    base = home if home is not None else Path.home()
    slug = str(repo_root).replace("/", "-")
    return base / ".claude" / "projects" / slug


def _parse_timestamp(value: object) -> datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def _critic_prompts_in_file(path: Path, since: datetime) -> Iterator[str]:
    """Yield the prompt of every prose-critic Agent call in ``path`` newer than ``since``."""
    try:
        text = path.read_text(errors="replace")
    except OSError:
        return
    for line in text.splitlines():
        # Cheap prefilter: transcripts run to megabytes and almost no line matches.
        if CRITIC_AGENT not in line:
            continue
        try:
            record = json.loads(line)
        except ValueError:
            continue
        if not isinstance(record, dict):
            continue
        stamp = _parse_timestamp(record.get("timestamp"))
        if stamp is None or stamp < since:
            continue
        message = record.get("message")
        if not isinstance(message, dict):
            continue
        content = message.get("content")
        if not isinstance(content, list):
            continue
        for block in content:
            if not isinstance(block, dict) or block.get("type") != "tool_use":
                continue
            if block.get("name") not in AGENT_TOOL_NAMES:
                continue
            payload = block.get("input")
            if not isinstance(payload, dict):
                continue
            if payload.get("subagent_type") != CRITIC_AGENT:
                continue
            prompt = payload.get("prompt")
            if isinstance(prompt, str):
                yield prompt


def critic_prompts(tdir: Path, since: datetime) -> list[str]:
    """Prompts of every prose-critic run recorded in ``tdir`` since ``since``.

    Transcripts whose mtime predates ``since`` cannot hold a newer record, so
    they are skipped without being read.
    """
    if not tdir.is_dir():
        return []
    prompts: list[str] = []
    for path in sorted(tdir.glob("*.jsonl")):
        try:
            mtime = datetime.fromtimestamp(path.stat().st_mtime, tz=UTC)
        except OSError:
            continue
        if mtime < since:
            continue
        prompts.extend(_critic_prompts_in_file(path, since))
    return prompts


def uncritiqued(files: Iterable[str], prompts: Iterable[str]) -> list[str]:
    """Staged files no prompt mentions.

    A prompt names its file by absolute path, which contains the repo-relative
    path as a substring, so substring matching covers both forms.
    """
    prompt_list = list(prompts)
    return [f for f in files if not any(f in prompt for prompt in prompt_list)]


def has_transcripts(tdir: Path) -> bool:
    return tdir.is_dir() and any(tdir.glob("*.jsonl"))


def main() -> int:
    repo_root = Path(_git(Path.cwd(), "rev-parse", "--show-toplevel").strip() or Path.cwd())

    files = staged_content_files(repo_root)
    if not files:
        return 0

    if os.environ.get(BYPASS_ENV):
        print(
            f"\n=== pre-commit: prose-critic gate BYPASSED ({BYPASS_ENV} set) ===\n"
            "The critic did not run on these staged content files:",
            file=sys.stderr,
        )
        for path in files:
            print(f"  {path}", file=sys.stderr)
        return 0

    tdir = transcript_dir(repo_root)
    if not has_transcripts(tdir):
        # Nothing to verify against — a hand commit, a fresh clone, or a
        # container. Passing here is the fail-open half of the design.
        return 0

    since = head_commit_time(repo_root)
    missing = uncritiqued(files, critic_prompts(tdir, since))
    if not missing:
        return 0

    print(
        "\n=== pre-commit: prose-critic gate FAILED ===\n"
        "No prose-critic run since the last commit covers these staged files:",
        file=sys.stderr,
    )
    for path in missing:
        print(f"  {path}", file=sys.stderr)
    print(
        "\nRun the prose-critic subagent on each one and apply what it flags, then\n"
        "commit again. CLAUDE.md requires this on all new or edited content prose,\n"
        "and it overrides any session instruction against spawning subagents.\n"
        f"For a mechanical sweep with no new prose, set {BYPASS_ENV}=1 — it lets the\n"
        "commit through and says so on the way past. Do not use --no-verify.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
